account/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^login/$', views.log_in),
    url(r'^logout/$', views.log_out),
    url(r'^profile/$', views.profile),

)

institution/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.index),
    
    #groups
    url(r'^groups/$', views.groups, name="groups"),
    #url(r'^groups/new$', views.groups_new, name="groups_new"),

    #grades
    url(r'^grades/$', views.grades, name="grades"),
    #url(r'^grades/new$', views.grades_new, name="grades_new"),
)

school/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

#admin.autodiscover() #investigar

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'school.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('account.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^institution/', include('institution.urls', namespace="institution")),
    url(r'^students/', include('student.urls', namespace="students")),
)

student/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.index, name="index"),
	url(r'^(?P<pk>[0-9]+)/$', views.show, name="show"),
	url(r'^new/$', views.new, name='new'),
	url(r'^(?P<pk>[0-9]+)/edit/$', views.edit, name="edit"),
)

account/models.py
from django.db import models

# Create your models here.

institution/models.py
from django.db import models

# class TipoOrganizacion(models.Model):
#     descripcion = models.CharField(max_length=140)
#     es_activo = models.BooleanField(default=True)
#     fecha_registro = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.descripcion

class Institution(models.Model):
    name                = models.CharField(max_length=140)
    slug                = models.SlugField()
    description         = models.TextField()
    #logo               = models.ImageField()
    status              = models.BooleanField(default=True)
    registration_date   = models.DateTimeField(auto_now_add=True)
    address             = models.TextField()
    phone_number        = models.CharField(max_length=30)
    # tipo_organizacion = models.ForeignKey(TipoOrganizacion)

    def save(self):
        self.slug = slugify(self.slug)
        super(test, self).save()

    def __str__(self):
        return self.nombre

class Grade(models.Model):
    name        = models.CharField(max_length=140)
    description = models.TextField()
    status      = models.BooleanField(default=True)

# class Clase(models.Model):
#     nombre = models.CharField(max_length=140)
#     descripcion = models.TextField()
#     es_activo = models.BooleanField(default=True)
#     fecha_registro = models.DateTimeField(auto_now_add=True)

class Group(models.Model):
    name        = models.CharField(max_length=140)
    description = models.TextField()
    # grado = models.ForeignKey(Grado)
    # clases = models.ManyToManyField(Clase, through='ClaseGrupo')
    # es_activo = models.BooleanField(default=True)
    # fecha_registro = models.DateTimeField(auto_now_add=True)

# class ClaseGrupo(models.Model):
#     grupo = models.ForeignKey(Grupo)
#     clase = models.ForeignKey(Clase)
#     fecha_registro = models.DateTimeField(auto_now_add=True)

student/models.py
from django.db import models

class Student(models.Model):
    name          	= models.CharField(max_length=50)
    last_name       = models.CharField(max_length=140)
    # grupo           = models.ForeignKey(Grupo)
    status       	= models.BooleanField(default=True)
    register_date  	= models.DateTimeField(auto_now_add=True)

    # def save (self):
    # 	self.slug = slugify(self.slug)
    # 	super(test, self).save()

    def __str__ (self):
    	return self.name

task/models.py
from django.db import models

class Task (models.Model):
	name = models.CharField(max_lenght)
# Create your models here.

account/forms/user.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(label='Contrasena', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username','email','password',)

account/views.py
from django.shortcuts import render,redirect,render_to_response,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from .forms import UserForm
from django.contrib.auth.models import User


# @login_required()
def index(request):
     return render(request,'index/index.html',locals())


#Auth views
def log_in(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('account.views.index'))
            else:
                return HttpResponse("Cuenta desactivada.")
        else:
            message = "Datos incorrectos"
            return render(request,'account/login.html', locals())

    else:
        return render_to_response('account/login.html', {}, context)

@login_required
def log_out(request):
    logout(request)
    return redirect(reverse(login))

@login_required
def profile(request):
    post = get_object_or_404(User, pk=request.user.pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=post)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(user.password)
            user.save()
            return redirect(reverse('account.views.profile'))
    else:
        form = UserForm(instance=post)
    return render(request, 'account/profile.html', locals())

institution/views.py
from django.shortcuts import render

# @login_required()
def index(request):
    return render(request,'institution/index.html', locals())

def groups(request):
	return render(request, 'institution/groups/index.html');

def grades(request):
	return render(request, 'institution/grades/index.html')

student/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Student
from .forms import StudentForm
import json
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index (request):
	students = Student.objects.order_by('-id')
	page = request.GET.get('page')
	paginator = Paginator(students, 10)
	try:
		students = paginator.page(page)
	except PageNotAnInteger:
		students = paginator.page(1)
	except EmptyPage:
		students = paginator.page(paginator.num_pages)

	#if request.is_ajax():
	#	return render(request, 'students/students.html', { 'students' : students })

	return render(request, 'students/index.html', { 'students' : students })

def new (request):
	if request.method == "POST":
		try:
			form = StudentForm(request.POST)
			if form.is_valid():
				student = form.save(commit=False)
				student.save()
				data = {}
				data['msg'] = 'student created'
				data['success'] = True
				return HttpResponse(json.dumps(data), content_type="application/json")
			else:
				return HttpResponse(json.dumps(data), content_type="application/json")
				#return errors
		except Exception, e:
			return e
			#return exception 
	else:
		form = StudentForm()
	return render(request, 'students/new.html', { 'form' : form })

def show (request, pk):
	return render(request, 'students/show.html')

def edit (request, pk):
	student = get_object_or_404(Student, pk=pk)
	if request.method == 'POST':
		form = StudentForm(request.POST, instance=student)
		data = {}
		if form.is_valid():
			student = form.save(commit=False)
			student.save()
			data['msg'] = 'student updated'
			data['success'] = True
		else:
			data['msg'] = 'student error'
			data['success'] = False
		return HttpResponse(json.dumps(data), content_type="application/json")
	else:
		form = StudentForm(instance=student)
		return render(request, 'students/edit.html', {'form' : form, 'student' : student })

task/views.py
from django.shortcuts import render

# Create your views here.

account/templates/index/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1 class="page-header">Dashboard</h1>

    <div class="row placeholders">
        <div class="col-xs-6 col-sm-3 placeholder">
            <img data-holder-rendered="true"
                 src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc1LjUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6I0ZGRkZGRjtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg=="
                 data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200">
            <h4>Label</h4>
            <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
            <img data-holder-rendered="true"
                 src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc1LjUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6IzFFMjkyQztmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg=="
                 data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200">
            <h4>Label</h4>
            <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
            <img data-holder-rendered="true"
                 src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc1LjUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6I0ZGRkZGRjtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg=="
                 data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200">
            <h4>Label</h4>
            <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
            <img data-holder-rendered="true"
                 src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc1LjUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6IzFFMjkyQztmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg=="
                 data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200">
            <h4>Label</h4>
            <span class="text-muted">Something else</span>
        </div>
    </div>

    <h2 class="sub-header">Section title</h2>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1,001</td>
                <td>Lorem</td>
                <td>ipsum</td>
                <td>dolor</td>
                <td>sit</td>
            </tr>
            <tr>
                <td>1,002</td>
                <td>amet</td>
                <td>consectetur</td>
                <td>adipiscing</td>
                <td>elit</td>
            </tr>
            <tr>
                <td>1,003</td>
                <td>Integer</td>
                <td>nec</td>
                <td>odio</td>
                <td>Praesent</td>
            </tr>
            <tr>
                <td>1,003</td>
                <td>libero</td>
                <td>Sed</td>
                <td>cursus</td>
                <td>ante</td>
            </tr>
            <tr>
                <td>1,004</td>
                <td>dapibus</td>
                <td>diam</td>
                <td>Sed</td>
                <td>nisi</td>
            </tr>
            <tr>
                <td>1,005</td>
                <td>Nulla</td>
                <td>quis</td>
                <td>sem</td>
                <td>at</td>
            </tr>
            <tr>
                <td>1,006</td>
                <td>nibh</td>
                <td>elementum</td>
                <td>imperdiet</td>
                <td>Duis</td>
            </tr>
            <tr>
                <td>1,007</td>
                <td>sagittis</td>
                <td>ipsum</td>
                <td>Praesent</td>
                <td>mauris</td>
            </tr>
            <tr>
                <td>1,008</td>
                <td>Fusce</td>
                <td>nec</td>
                <td>tellus</td>
                <td>sed</td>
            </tr>
            <tr>
                <td>1,009</td>
                <td>augue</td>
                <td>semper</td>
                <td>porta</td>
                <td>Mauris</td>
            </tr>
            <tr>
                <td>1,010</td>
                <td>massa</td>
                <td>Vestibulum</td>
                <td>lacinia</td>
                <td>arcu</td>
            </tr>
            <tr>
                <td>1,011</td>
                <td>eget</td>
                <td>nulla</td>
                <td>Class</td>
                <td>aptent</td>
            </tr>
            <tr>
                <td>1,012</td>
                <td>taciti</td>
                <td>sociosqu</td>
                <td>ad</td>
                <td>litora</td>
            </tr>
            <tr>
                <td>1,013</td>
                <td>torquent</td>
                <td>per</td>
                <td>conubia</td>
                <td>nostra</td>
            </tr>
            <tr>
                <td>1,014</td>
                <td>per</td>
                <td>inceptos</td>
                <td>himenaeos</td>
                <td>Curabitur</td>
            </tr>
            <tr>
                <td>1,015</td>
                <td>sodales</td>
                <td>ligula</td>
                <td>in</td>
                <td>libero</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

account/templates/layouts/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="image_src" type="image/jpeg" href=" ">

    <!-- Site Properities -->
    <meta name="description" content=" ">
    <meta name="keywords" content=" ">

    <title>Zativa - School system</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}"/>

    <link rel="stylesheet" href="{% static "css/app.css" %}"/>
    <link rel="stylesheet" href="{% static "css/theme.css" %}"/>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'account.views.index' %}"><strong>{{ APP|slice:":1" }}</strong><span>{{ APP|slice:"1:" }}</span></a></a>
        </div>
        <ul class="nav navbar-nav left-controls">
            <li><a href="#" id="dashboard-actions"><i class="glyphicon glyphicon-menu-hamburger"></i></a></li>
        </ul>
        <div style="height: 1px;" aria-expanded="false" id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.first_name }} {{ user.last_name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'account.views.profile' %}">Perfil</a></li>
                        <li><a href="#">Ajustes</a></li>
                        <li><a href="#">Mensajes</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'account.views.log_out' %}">Salir</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <input class="form-control search" placeholder="Buscar..." type="text">
            </form>

        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" id="sidebar">
            <div class="profile">
                <div class="placeholder">
                    <img class="img-responsive" data-holder-rendered="true"
                         src="https://avatars3.githubusercontent.com/u/1274057?v=3&s=460"
                         data-src="holder.js/200x200/auto/sky" alt="200x200">
                </div>
                <div class="info">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ user.first_name }} {{ user.last_name }}
                            <small style="display: block;">Student of engineer</small>
                        </a>
                    </li>
                </div>
            </div>
            <ul class="nav nav-sidebar">
                <li><a href="" class="active"><i class="glyphicon glyphicon-user"></i><span>Alumnos</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-blackboard"></i><span>Clases</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-th"></i><span>Grupos</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-file"></i><span>Reportes</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-credit-card"></i><span>Pagos</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-inbox"></i><span>Mensajes</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-paperclip"></i><span>Archivos</span></a></li>
                <li><a href=""><i class="glyphicon glyphicon-cog"></i><span>Configuraci&oacute;n</span></a></li>
            </ul>
        </div>
        <div class="col-lg-10 col-sm-offset-3 col-lg-offset-2 col-md-10 col-md-offset-2 main" id="content">
            <div class="inner">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
<script type="application/javascript" src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
<script type="application/javascript" src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
<script type="application/javascript" src="{% static "js/Dashboard/dashboard.js" %}"></script>
</body>
</html>

templates/index/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <h2 class="sub-header">Section title</h2>

    <!-- <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1,001</td>
                <td>Lorem</td>
                <td>ipsum</td>
                <td>dolor</td>
                <td>sit</td>
            </tr>
            </tbody>
        </table>
    </div> -->

{% endblock %}

templates/institution/grades/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <h2 class="sub-header">Grados</h2>

    <!-- <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1,001</td>
                <td>Lorem</td>
                <td>ipsum</td>
                <td>dolor</td>
                <td>sit</td>
            </tr>
            </tbody>
        </table>
    </div> -->

{% endblock %}

templates/institution/groups/index.html
{% extends 'layouts/base.html' %}
{% block content %}

	<h1>Grupos</h1>

{% endblock %}

templates/layouts/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="image_src" type="image/jpeg" href="">

    <!-- Site Properities -->
    <meta name="description" content=" ">
    <meta name="keywords" content=" ">

    <title>School system</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "css/sidebar.css" %}"/>
    <link rel="stylesheet" href="{% static "css/table.css" %}"/>
    <link rel="stylesheet" href="{% static "css/h.css" %}"/>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" href="#">Project name</a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="#">Dashboard</a></li>
            <li>
                <a href="{% url 'students:index' %}" class="active">
                    <i class="glyphicon glyphicon-user"> Alumnos </i>
                </a>
            </li>
            <li><a href="#"><i class="glyphicon glyphicon-education"> Docentes</i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-blackboard"> Materias </i></a></li>
            <li>
                <a href="{% url 'institution:groups'%}">
                    <i class="glyphicon glyphicon-th"> Grupos </i>
                </a>
            </li>
            <li>
                <a href="{% url 'institution:grades'%}">
                    <i class="glyphicon glyphicon-th-list"> Grados </i>
                </a>
            </li>
            <li><a href="#"><i class="glyphicon glyphicon-bookmark"> Ciclos escolares</i></a></li>
            <li><a href="#"><i class="glyphicon glyphicon-paperclip"> Archivos </i></a></li>
            <li><a href="#"><i class="glyphicon glyphicon-book"> Tareas</i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-credit-card"> Pagos </i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-inbox"> Mensajes </i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-cog"> Configuraci&oacute;n </i></a></li>
            <li><a href="#"><i class="glyphicon glyphicon-question-sign"> Ayuda</i></a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>


    <script type="application/javascript" src="{% static "vendors/jquery/dist/jquery.js" %}"></script>
    <script type="application/javascript" src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/dashboard/table.js" %}"></script>
    <script type="application/javascript" src="{% static "js/dashboard/dashboard.js" %}"></script>
    <script type="application/javascript" src="{% static "js/dashboard/students.js" %}"></script>
    <script type="application/javascript" src="{% static "js/jquery.form.js" %}"></script>
    <script type="application/javascript" src="{% static "js/jquery.validate.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/bootbox.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/dashboard/helpers.js" %}"></script>
</body>
</html>

templates/students/edit.html
<form method="POST" action="{% url 'students:edit' student.id %}" class="form-student" id="form-student">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title" id="myModalLabel">New student</h4>
	</div>
	<div class="modal-body">
		{% csrf_token %}
		{{ form.as_p }}
	</div>
	<div class="modal-footer">
	  	<button type="submit" id="btn-modal-save" class="save btn btn-success">Save</button>
		<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
	</div>
</form>